### ISSUE TITLE
rocfft_aot_helper input checking

### ISSUE THREAD

**Issue by trixirt** [ROCm/rocFFT#430] opened 2023-07-13 18:54 UTC
There are several problems

On Fedora, building rocFFT master branch against Fedora's ROCm packages
There is this failure

FAILED: library/src/rocfft_kernel_cache.db /home/trix/work/rocm/rocFFT/build/library/src/rocfft_kernel_cache.db                                            
cd /home/trix/work/rocm/rocFFT/build/library/src && /home/trix/work/rocm/rocFFT/build/library/src/rocfft_aot_helper "" /home/trix/work/rocm/rocFFT/build/library/src/rocfft_kernel_cache.db /home/trix/work/rocm/rocFFT/build/library/src/rocfft_rtc_helper gfx906 gfx908 gfx90a gfx1030 gfx1100 gfx1101 gfx1102

Which maps to this command
COMMAND rocfft_aot_helper \"${ROCFFT_BUILD_KERNEL_CACHE_PATH}\" ${ROCFFT_KERNEL_CACHE_PATH} $<TARGET_FILE:rocfft_rtc_helper> ${AMDGPU_TARGETS_AOT}

The cmake variable ROCFFT_BUILD_KERNEL_CACHE_PATH is required but not checked for.

The input checking on rocfft_aot_helper does not cache this because it is only

int main(int argc, char** argv)                                                                                                                            
{                                                                                                                                                          
    if(argc < 5)                                                                                                                                           
    {                                                                                                                                                      
        puts("Usage: rocfft_aot_helper temp_cachefile.db output_cachefile.db "                                                                             
             "path/to/rocfft_rtc_helper gfx000 gfx001 ...");                                                                                               
        return 1;                                                                                                                                          
    }  

This checking should be improved to check if arguments intended to be files are files and gpu target are targets.
 
If this offline compiling is optional, and it seems to be, then it should be controlled by some cmake variable like rocBLAS does with -DBUILD_WITH_TENSILE=OFF

**Comment by evetsso** [comment] 2023-07-13 19:48
Hi @trixirt , thanks for the bug report.

Do you have the whole build log, and can you attach it here if so?  It seems likely that this is the same issue as #422, so I would like to confirm if the process is segfaulting.

rocfft_aot_helper should already be gracefully handling an empty ROCFFT_BUILD_KERNEL_CACHE_PATH, so I'm skeptical that this is the root cause of your problem.

**Comment by cgmb** [comment] 2023-07-14 18:52
> rocfft_aot_helper should already be gracefully handling an empty ROCFFT_BUILD_KERNEL_CACHE_PATH

I haven't tried with rocfft from ROCm 5.6, but I can confirm that it did in ROCm 5.5.

**Comment by evetsso** [comment] 2023-07-14 20:03
ROCFFT_BUILD_KERNEL_CACHE_PATH is optional and allowed to be empty.  It could be documented better, but AFAICT it's not related to the problem you're observing.

It sounds like the segfault in #422 is the root cause here.  Modifying the build to not generate the cache will bypass the segfault at build time.  But even though that would work, I don't think Fedora (or anyone) should seriously consider doing this, as it would mean:
* commonly used FFT kernels will always need to be compiled at runtime, and
* it's likely that the compilation at runtime will fail in the same way anyway.
 
The effort would be better spent, I think, on fixing the root cause.

**Comment by sgueko** [comment] 2023-12-23 20:53
this is due to the removal of unsupported GPUs like gfx803 and gfx900 in library/src/CMakeList.txt 

[`Here`](https://github.com/ROCm/rocFFT/blob/aec0ff71f3d3e79b89e0aa7a76783ac14f2122aa/library/src/CMakeLists.txt#L540)

this issue can be fixed by add or specifying a supported GPU with -DAMDGPU_TARGETS="gfx90a"

**Comment by evetsso** [comment] 2024-03-11 15:41
Closing, as the root cause here was in #422.  984913b287b460da0d7ea08c56432de974b1dce6 has further clarified that an empty value for ROCFFT_BUILD_KERNEL_CACHE_PATH is allowed, which should address the confusion here.

**Closed by evetsso** 2024-03-11 15:41 UTC
